version: 3.0.0.{build}
image: Visual Studio 2022
init:
- cmd: sqlcmd -S "(localdb)\MSSQLLocalDB" -Q "CREATE DATABASE bitpantry.processlock.tests"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: false
  verbosity: minimal
deploy:
- provider: Environment
  name: BitPantry NuGet
  on:
    branch: master